const appName = 'Grocery Store';
export default {
  title_home: 'Home',
  title_dashboard: 'Dashboard',
  title_notifications: 'Notifications',
  next: 'Next',
  skip: 'Skip',
  start: 'Start',
  city_prompt: 'Choose a city',
  company_prompt: 'Choose a company',
  cafeteria_prompt: 'Choose a cafeteria',
  login_text: 'SignIn',
  login_text1: 'SignIn to Grocery App',
  login_text2: ' enter email & password to continue',
  forgot_text1: 'Reset Your Password',
  forgot_text2: 'you need One Time Password to reset password',
  signup_text: 'SignUp',
  signup_text1: 'Welcome to Grocery App',
  signup_text2: "Let's get started",
  mobileHint: 'Enter Mobile Number',
  passwordHint: 'Enter Password',
  confPasswordHint: 'Enter Confirm Password',
  nameHint: 'Enter Name',
  emailHint: 'Enter Email',
  numberHint: '0123-456-789',
  signup: 'SIGNUP',
  signin: 'SIGNIN',
  sendOTP: 'SEND OTP',
  resetpassword: 'Reset Password',
  forgetPassword: 'Forgot Password ?',
  otpText: 'OTP Verification',
  otpSendText: 'We will send you One Time Password on this mobile number',
  otpSendMobile: `Enter OTP send to mobile`,
  enterMobile: 'Enter Mobile Number',
  generateOTP: 'Send OTP',
  verifyOTP: 'Verify OTP',
  notReceiveOTP: "don't receive the OTP",
  resendOTP: 'Resend OTP',
  id: 0,
  lang: 'English',
  langCode: 'en',
  appName: 'PushBase',
  signinTitle: 'Signin to Get Started!',
  email: 'Email',
  name: 'Name',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  createAcc: 'Create Account',
  forgot: 'Forgot Password',

  reset: 'Reset',
  logout: 'Logout',

  home: 'Home',
  categories: 'Categories',
  settings: 'Settings',

  // App intro sliders
  slide1Title: 'SAMPLE TITLE 1',
  slide1Text: 'This is sample description 1',
  slide2Title: 'SAMPLE TITLE 2',
  slide2Text: 'This is sample description 2',
  slide3Title: 'SAMPLE TITLE 3',
  slide3Text: 'This is sample description 3',

  //Validation messages
  required: 'is required',
  notValid: 'is not valid',
  tooShort: 'Minimum {count, number} chars required',
  doesntMatch: "doesn't match",

  nameErrorMessage: 'Enter your correct name',
  mobileErrorMessage: 'Enter correct mobile number',
  passwordErrorMessage: 'Enter 8 character password',
  confirmPasswordErrorMessage: 'Password and confirm password must be same',
  successfullVerify: 'Successfully verified your Mobile Number',
  enterValidOTP: 'Please enter valid OTP send to your Mobile Number',
  passwordResetSuccess: 'Password successfully reset',
  searchHint: 'Search here...',
  addressHint: 'Enter Address',
  cityHint: 'Enter City',
  stateHint: 'Enter State',
  save: 'Save',
};
